name: "release ci"

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  push:
    branches:
      - main
      - alpha
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: string

jobs:
  release-pub:
    name: "release-pub"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: install node js
        uses: actions/setup-node@v2
        with:
          node-version: '18.9.0'
      - name: npm install
        run: npm install
      - name: lerna bootstrap
        run: npm run bootstrap
      - name: semantic publish
        run: npm run semantic
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      - name: lb-demo upgrade
        run: |
          npm run updemo
          git config --global user.email "efficiency-helper[bot]@users.noreply.github.com"
          git config --global user.name "efficiency-helper[bot]"
          git add packages/lb-demo/package.json
          git commit -m "feat(ci): upgrade lb-demo dependence version"
          git push
