name: "test env"

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  push:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: string

jobs:
  release-pub:
    name: "test env"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: get github branch info
        run: |
          echo ${{ github.action }}
          echo ${{ github.action_path }}
          echo ${{ github.action_ref }}
          echo ${{ github.action_repository }}
          echo ${{ github.action_status }}
          echo ${{ github.actor }}
          echo ${{ github.actor_id }}
          echo ${{ github.api_url }}
          echo ${{ github.base_ref }}
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.repository }}
          echo ${{ github.repositoryUrl }}
          echo ${{ github.token }}
